package massim.javaagents.massimworld.actions;

import eis.iilang.Action;
import massim.javaagents.massimworld.map.Coordinates;

/**
 * The supertype of all actions generated by this javaagents implementation,
 * provides an abstract method for creating an eis.iilang.Action given to the scheduler.
 * The subclasses are named according to the massim documentation
 * {@see https://github.com/agentcontest/massim_2022/blob/main/docs/scenario.md#actions}.
 */
public abstract class MassimAction {

    /**
     * Returns the move offset of an action in relative coordinates if the action was succesfull.
     * Differs only for the MoveAction from Coordinates.ZERO.
     * @return the relative shift of an agent by successful execution.
     */
    public Coordinates getMoveOffset() {
        return Coordinates.ZERO;
    }

    /**
     * Creates the corresponding eis.lang.Action.
     * @return eis.lang.Action
     */
    public abstract Action createEisAction();

}